name: 03 - Workflow Runners

on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
        echo "This job is running on Ubuntu Runner"
        echo "Runner OS: $RUNNER_OS" #This stores env details where your runner is running
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        run:
          echo "This job is running on Windows Server"
  mac-echo:
    runs-on: macos-latest
    steps:
      - name: Show OS
        echo "This job is running on MACOS"


        
