name: 06 - contexts
run-name: 06 - contexts | DEBUG - ${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs: 
      debug:
        type: boolean
        default: false

env:
   MY_WORKFLOW_VAR: 'workflow'
   MY_OVERWRITTEN_VAR: 'workflow'
   

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
       MY_JOB_VAR: 'job'
       MY_OVERWRITTEN_VAR: 'job'
    steps:
      - name: Display Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
          
      - name: Retrieve Variable
        run: |
          # Assuming MY_VAR is an environment variable
          echo "Variable value is: ${{ vars.MY_VAR }}"

      - name: Print Env Variables
        env:
           MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
          
        # If MY_VAR is defined in secrets, use the following instead:
        # echo "Secret value is: ${{ secrets.MY_VAR }}"
