name: 06 - contexts
run-name: 06 - contexts | DEBUG - ${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs: 
      debug:
        type: boolean
        default: false

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
          
      - name: Retrieve Variable
        run: |
          # Assuming MY_VAR is an environment variable
          echo "Variable value is: ${{ vars.MY_VAR }}"
          
        # If MY_VAR is defined in secrets, use the following instead:
        # echo "Secret value is: ${{ secrets.MY_VAR }}"
