name: 14 - working with artifacts

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    steps:
        - name: Checkout code
          used: actions/checkout@v4
        - name: Setup Node
          uses: action/setup-node@v3
          with:
            nodeversion: '20.x'
        - name: Download cached dependencies
          uses: actions/cache@v3
          id: cache
          with:
            path: 14-artifacts/react-app/node_modules
            key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
        - name: Install dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: npm ci
        - name: Unit-test
          run: npm run test
        - name: Build Code
          run: npm run build
        - name: Upload build files
          run: actions/upload-artifacts@v3
          with:
            name: app
            path: 14-artifacts/react-/build

  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Download artifacts
          uses: actions/download-artifacts@v3
          with:
            name: app
            patch: buils
        - name: Show folder structure
          run: ls -R
