name: 16 - Working with Environments

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging


jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default_value' }}
    steps:
      - name: Echo Vars
        run:  |
          echo "Env Variables: ${{ env.MY_ENV_VALUE }}"