name:  17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - S{{ input.target-env }}
 
on:
  workflow_dispatch:
    inputs:
      target-env:
        description: Which environment to target for dependency installation
        type: choice
        options:
          - development
          - production

env:
    working-directory: 17-custom-actions/react-app 

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node and NPM Dependencies
        uses: ./.github/action/composite-cache-deps
        with:
            node-version: 20.x
            working-dir: ${{ env.working-directory }}
            target-env: ${{ inputs.target-env }}
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build