name:  17 - 1 - Custom Actions - Composite 
 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node and NPM Dependencies
        uses: ./.github/action/composite-cache-deps
        with:
            node-version: 20.x
            working-dir: .
            