name:  17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS
 
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for dependency updates
        uses: ./.github/action/js-dependency-update
 