name:  17 - 3 - Custom Actions - Docker
run-name: 17 - 3 - Custom Actions - Docker | env - S{{ input.target-env }}
 
on:
  workflow_dispatch:
    inputs:
      url:
        type: string
        default: 'https://www.google.com'
        max_trials:
          description: Maximum number of trials action fails.
          default: '10'
          required false
        delay:
          description: Delay in seconds between trials.
          default: '5'
          required: false

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/action/docker-ping-url
        with:
          url: ${{ inputs.url }}

