name: 19 - 1 - Managing Concurrency

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        id: ping URL
        uses: ./.github/action/docker-ping-url
        with:
          url: https://www.invalidurlsdsdsdfdf.com
          max_trials: 5
          delay: 2