name: 19 - 2 - Managing Concurrency

on:
  workflow_dispatch:


jobs:
  ping-with-concurrency:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        id: ping-URL
        uses: ./.github/action/docker-ping-url
        with:
          url: https://www.invalidurlsdsdsdfdf.com
          max_trials: 20
          delay: 2

  ping-without-concurrency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        id: ping-URL
        uses: ./.github/action/docker-ping-url
        with:
          url: https://www.invalidurlsdsdsdfdf.com
          max_trials: 20
          delay: 2